In [2]:
import numpy as np 
import pandas as pd 
import os
import gc
import psutil

In [3]:
print(os.listdir('E:\\kaggle\\Avito Demand Prediction Challenge'))

['avito_region_city_features.csv', 'cc.ru.300.vec', 'cc.ru.300.vec.zip', 'city_population_wiki_v3.csv', 'code', 'code.zip', 'feature.py', 'featureh.py', 'features', 'image', 'image features', 'periods_test.csv', 'periods_test.csv.zip', 'periods_train.csv', 'periods_train.csv.zip', 'region.csv', 'ru', 'ru.zip', 'test.csv', 'test.csv.zip', 'test.zip', 'test_active.csv', 'test_active.csv.zip', 'test_jpg', 'test_jpg.zip', 'train.csv', 'train.csv.zip', 'train_active.csv', 'train_active.csv.zip', 'train_jpg_0', 'train_jpg_0.zip', 'train_jpg_1', 'train_jpg_1.zip', 'train_jpg_2', 'train_jpg_2.zip', 'train_jpg_3', 'train_jpg_3.zip', 'train_jpg_4', 'train_jpg_4.zip']

In [3]:
columns=['item_id','user_id','activation_date']
#columns=['item_id','user_id']
path='E:\\kaggle\\Avito Demand Prediction Challenge\\'
test=pd.read_csv(path+'test.csv',header=0,skipinitialspace=True, usecols=columns)
train=pd.read_csv(path+'train.csv',header=0,skipinitialspace=True, usecols=columns)
data=pd.concat([train,test],ignore_index=True)
del train,test
gc.collect()

test=pd.read_csv(path+'test_active.csv',header=0,skipinitialspace=True, usecols=columns)
train=pd.read_csv(path+'train_active.csv',header=0,skipinitialspace=True, usecols=columns)
data=pd.concat([data,train,test],ignore_index=True)
del train,test
gc.collect()
data

14

In [ ]:
result=data.groupby(['user_id']).item_id.nunique().reset_index()
result.columns.values[1]='item_num'
result.to_csv('usernum.csv', index=False)
result

In [2]:
columns=['item_id','user_id']
path='E:\\kaggle\\Avito Demand Prediction Challenge\\'
test=pd.read_csv(path+'test_active.csv',header=0,skipinitialspace=True, usecols=columns)
train=pd.read_csv(path+'train_active.csv',header=0,skipinitialspace=True, usecols=columns)
data=pd.concat([train,test],ignore_index=True)
data['temp']=0
data=data.groupby(['item_id','user_id']).temp.size().reset_index()
data.columns.values[2]='temp'
data=data.drop(['temp'], axis=1)
del train,test
gc.collect()

columns=['item_id','activation_date']
test=pd.read_csv(path+'periods_test.csv',header=0,skipinitialspace=True, usecols=columns)
train=pd.read_csv(path+'periods_train.csv',header=0,skipinitialspace=True, usecols=columns)
period=pd.concat([train,test],ignore_index=True)
del train,test
gc.collect()
period

               item_id activation_date
0         8f5caef7afb0      2017-02-14
1         66218ff526d1      2017-02-16
2         b237d9539b21      2017-03-01
3         80bf58082ad3      2017-03-19
4         67a9944a7373      2017-03-14
5         47081d25b7cb      2017-02-19
6         5a328b4a8be1      2017-02-20
7         87292b76e4e1      2017-03-17
8         2ccefc8a940b      2017-02-19
9         ded64e61cd85      2017-03-13
10        0d37e6b46385      2017-03-01
11        185fb5e63198      2017-02-28
12        8b3d613b4120      2017-03-16
13        b679b52f008b      2017-03-17
14        6775c05a8a1b      2017-03-15
15        6527076f08cf      2017-03-02
16        220ba45e7a83      2017-02-21
17        10ffc62e5c63      2017-03-16
18        972b768117da      2017-03-10
19        4d5154a95d5d      2017-03-16
20        007471b97f31      2017-03-04
21        2c9ee803dd81      2017-02-26
22        c64fa40fe5b8      2017-03-04
23        b58fe0464c5b      2017-02-26
24        ecd95991f26b      2017-03-21
25        2cb3982ec6bd      2017-02-28
26        9a05e06eab96      2017-02-26
27        a4eaa89e6b4f      2017-03-22
28        5525281202fd      2017-03-15
29        f0fbb973c81f      2017-03-12
...                ...             ...
30412304  ede5d42a0c0b      2017-04-17
30412305  c48bbeba70ed      2017-03-28
30412306  9d928a4ddc52      2017-03-28
30412307  b3120ffb4f7d      2017-04-11
30412308  372b6dac3dde      2017-04-10
30412309  e20ef1f07269      2017-03-21
30412310  147ebfd8f1a4      2017-03-16
30412311  9d0c8c9a21fe      2017-04-04
30412312  fa6805f8232d      2017-04-03
30412313  bd51776fca56      2017-04-08
30412314  6e67a2886875      2017-04-06
30412315  39c4f2436bdd      2017-04-13
30412316  1c895a5cd52b      2017-03-30
30412317  50ebef7ecde3      2017-04-03
30412318  f89e6e87b121      2017-04-01
30412319  d37029c7bbd1      2017-04-12
30412320  9e1f6c882bec      2017-04-16
30412321  38669cc738d8      2017-04-05
30412322  c68057453038      2017-03-17
30412323  62f65e482165      2017-04-16
30412324  ee804474c9de      2017-04-11
30412325  684a9e4b9e55      2017-03-30
30412326  1e3ed5030997      2017-03-14
30412327  5fea3cb8914e      2017-03-30
30412328  da7ef892f31e      2017-03-15
30412329  8c0033dfa9f8      2017-03-31
30412330  0dc7523352ea      2017-04-08
30412331  52ebbc53cc22      2017-03-16
30412332  8946dd819cb7      2017-04-02
30412333  7de9ce8bbac5      2017-03-31

[30412334 rows x 2 columns]

In [3]:
period=period.groupby(['item_id']).activation_date.size().reset_index()
period.columns.values[1]='edit_time'
gc.collect()
data=pd.merge(data, period, on=['item_id'],how='left')
del period
gc.collect()
data=data.fillna(1)
gc.collect()
data['edit_time']=data['edit_time']-1

sumcount=data.groupby(['user_id']).edit_time.sum().reset_index()
sumcount.columns.values[1]='edit_time'

count=data.groupby(['user_id']).item_id.nunique().reset_index()
count.columns.values[1]='count'

data=pd.merge(sumcount, count, on=['user_id'],how='left')
data['edit_time']=data['edit_time']/data['count']
data=data.drop(['count'], axis=1)
gc.collect()
data['edit_time']=round(data['edit_time'],3)

data.to_csv('usereditnum.csv', index=False)
data

              user_id  edit_time
0        00000077ff21      1.000
1        000006497719      1.000
2        00000b4d72f6      0.000
3        00000d642d7e      0.000
4        0000126b80a4      0.750
5        000014d301ab      0.000
6        0000159771bd      0.647
7        00001eaa1102      1.000
8        000021ea3738      0.000
9        000024fcf76d      1.000
10       00002578a209      1.000
11       0000295cd322      1.000
12       00002a6f1dea      0.000
13       00002f7b11f9      1.000
14       00002fb85cd6      0.000
15       0000326c6042      0.900
16       00003a4f0a97      1.000
17       000041bbfe14      0.887
18       00004558436e      0.500
19       00004b2abae7      0.429
20       00004b91004f      0.000
21       00005a5fd073      0.600
22       000060c77b42      0.000
23       000065c44938      0.000
24       00006be07ddf      0.889
25       00006d90c74d      1.000
26       00006ea4416a      0.087
27       00007116e8db      0.000
28       000079128027      1.000
29       00007ac91e3b      0.400
...               ...        ...
4015561  ffffb0cb5476      0.000
4015562  ffffbb859164      0.000
4015563  ffffc1cef067      1.118
4015564  ffffc389523e      0.000
4015565  ffffc8393a02      0.500
4015566  ffffcad6bfc7      1.000
4015567  ffffcb00d696      0.000
4015568  ffffce083b3e      0.000
4015569  ffffcf9581ae      1.000
4015570  ffffcfb8638b      0.000
4015571  ffffcff17df8      0.000
4015572  ffffd2be0576      0.000
4015573  ffffd4831cc9      0.750
4015574  ffffd52243f3      0.682
4015575  ffffd65021ed      0.000
4015576  ffffd65d6861      1.500
4015577  ffffd7aecc48      1.500
4015578  ffffdce81e7f      0.000
4015579  ffffe2e4205a      0.667
4015580  ffffe43e3a7e      0.000
4015581  ffffe8a7e9df      1.857
4015582  ffffe8ee9eff      0.000
4015583  ffffec376565      1.000
4015584  ffffee4e0e34      0.000
4015585  ffffef736394      0.000
4015586  fffff422303b      0.500
4015587  fffff4c76151      0.000
4015588  fffff869c33f      1.000
4015589  fffff926cb96      2.000
4015590  ffffff369d59      0.000

[4015591 rows x 2 columns]

In [4]:
columns=['item_id','user_id']
path='E:\\kaggle\\Avito Demand Prediction Challenge\\'
test=pd.read_csv(path+'test_active.csv',header=0,skipinitialspace=True, usecols=columns)
train=pd.read_csv(path+'train_active.csv',header=0,skipinitialspace=True, usecols=columns)
data=pd.concat([train,test],ignore_index=True)
data['temp']=0
data=data.groupby(['item_id','user_id']).temp.size().reset_index()
data.columns.values[2]='temp'
data=data.drop(['temp'], axis=1)
del train,test
gc.collect()

columns=['item_id','date_from','date_to']
test=pd.read_csv(path+'periods_test.csv',header=0,skipinitialspace=True, usecols=columns)
train=pd.read_csv(path+'periods_train.csv',header=0,skipinitialspace=True, usecols=columns)
period=pd.concat([train,test],ignore_index=True)
del train,test
gc.collect()
period

               item_id   date_from     date_to
0         8f5caef7afb0  2017-03-15  2017-03-16
1         66218ff526d1  2017-03-15  2017-03-18
2         b237d9539b21  2017-03-15  2017-03-28
3         80bf58082ad3  2017-03-19  2017-03-28
4         67a9944a7373  2017-03-15  2017-03-28
5         47081d25b7cb  2017-03-15  2017-03-20
6         5a328b4a8be1  2017-03-15  2017-03-21
7         87292b76e4e1  2017-03-17  2017-03-28
8         2ccefc8a940b  2017-03-15  2017-03-21
9         ded64e61cd85  2017-03-15  2017-03-28
10        0d37e6b46385  2017-03-15  2017-03-28
11        185fb5e63198  2017-03-15  2017-03-28
12        8b3d613b4120  2017-03-16  2017-03-28
13        b679b52f008b  2017-03-17  2017-03-28
14        6775c05a8a1b  2017-03-15  2017-03-28
15        6527076f08cf  2017-03-15  2017-03-28
16        220ba45e7a83  2017-03-15  2017-03-23
17        10ffc62e5c63  2017-03-16  2017-03-28
18        972b768117da  2017-03-15  2017-03-28
19        4d5154a95d5d  2017-03-16  2017-03-28
20        007471b97f31  2017-03-15  2017-03-26
21        2c9ee803dd81  2017-03-15  2017-03-28
22        c64fa40fe5b8  2017-03-15  2017-03-28
23        b58fe0464c5b  2017-03-15  2017-03-28
24        ecd95991f26b  2017-03-21  2017-03-28
25        2cb3982ec6bd  2017-03-15  2017-03-28
26        9a05e06eab96  2017-03-15  2017-03-28
27        a4eaa89e6b4f  2017-03-22  2017-03-28
28        5525281202fd  2017-03-15  2017-03-26
29        f0fbb973c81f  2017-03-15  2017-03-28
...                ...         ...         ...
30412304  ede5d42a0c0b  2017-04-17  2017-04-18
30412305  c48bbeba70ed  2017-04-12  2017-04-18
30412306  9d928a4ddc52  2017-04-12  2017-04-14
30412307  b3120ffb4f7d  2017-04-12  2017-04-18
30412308  372b6dac3dde  2017-04-12  2017-04-18
30412309  e20ef1f07269  2017-04-12  2017-04-18
30412310  147ebfd8f1a4  2017-04-12  2017-04-15
30412311  9d0c8c9a21fe  2017-04-12  2017-04-18
30412312  fa6805f8232d  2017-04-12  2017-04-18
30412313  bd51776fca56  2017-04-12  2017-04-18
30412314  6e67a2886875  2017-04-12  2017-04-18
30412315  39c4f2436bdd  2017-04-13  2017-04-18
30412316  1c895a5cd52b  2017-04-12  2017-04-18
30412317  50ebef7ecde3  2017-04-12  2017-04-18
30412318  f89e6e87b121  2017-04-12  2017-04-18
30412319  d37029c7bbd1  2017-04-12  2017-04-18
30412320  9e1f6c882bec  2017-04-16  2017-04-18
30412321  38669cc738d8  2017-04-12  2017-04-18
30412322  c68057453038  2017-04-12  2017-04-16
30412323  62f65e482165  2017-04-16  2017-04-18
30412324  ee804474c9de  2017-04-12  2017-04-18
30412325  684a9e4b9e55  2017-04-12  2017-04-18
30412326  1e3ed5030997  2017-04-12  2017-04-13
30412327  5fea3cb8914e  2017-04-12  2017-04-18
30412328  da7ef892f31e  2017-04-12  2017-04-14
30412329  8c0033dfa9f8  2017-04-12  2017-04-18
30412330  0dc7523352ea  2017-04-12  2017-04-18
30412331  52ebbc53cc22  2017-04-12  2017-04-18
30412332  8946dd819cb7  2017-04-12  2017-04-18
30412333  7de9ce8bbac5  2017-04-12  2017-04-18

[30412334 rows x 3 columns]

In [12]:
timeorigin=pd.to_datetime('2017-03-01')
period['date_from']=pd.to_datetime(period['date_from'], format="%Y-%m-%d")
period['date_to']=pd.to_datetime(period['date_to'], format="%Y-%m-%d")
period['dis_days']=(period['date_to']-period['date_from']).dt.days.astype('uint')
period=period.drop(['date_from','date_to'], axis=1)

period=period.groupby(['item_id']).dis_days.sum().reset_index()
period.columns.values[1]='dis_days'
gc.collect()
data=pd.merge(data, period, on=['item_id'],how='left')
del period
gc.collect()
data

               item_id       user_id  dis_days
0         00000077ff21  3c0ae6a131ee      13.0
1         000002c54018  ce6e0b01561c       6.0
2         000005570503  1bfc41de9f99       1.0
3         0000060018e6  cf4f54affdaf       6.0
4         000006497719  b3953ce33d94      19.0
5         000006f5c0fd  6e5030091e2d      11.0
6         0000079b5cc9  9c58891e3a23      14.0
7         000009bdb078  b9887843c97b      13.0
8         00000ae3f45d  f6cec0619759      16.0
9         00000b33142e  0fdb338ce67e      19.0
10        00000b4d72f6  3ab06769254f       5.0
11        00000d642d7e  48ee6fc3621f       2.0
12        00000e206c2b  726f32a099d8       7.0
13        00000e9980b0  9aa0456b05ab       7.0
14        00000f754712  ae90ad09ad6a      18.0
15        0000101fd3c1  534a4c024145      19.0
16        00001150005f  af8aec01f0b6       6.0
17        0000126b80a4  9e695bcaf327       9.0
18        000012aa550e  fb77f0fcc98b       1.0
19        000014ba2e9a  7d8aeacf5329       3.0
20        000014d301ab  9be478039086      19.0
21        0000159771bd  47d4ff261d99      19.0
22        00001820f04b  f225af3c483d       6.0
23        000018f41ad2  4a15f8641665      13.0
24        00001a1504bd  76a24c9fc922       5.0
25        00001b20a057  31294e4602a5      14.0
26        00001cc7e11f  45fe8ad0488b      18.0
27        00001df5fd75  b5974659d029      18.0
28        00001eaa1102  fa877a5b4d85      13.0
29        000020805367  b74bed83086a      15.0
...                ...           ...       ...
17453124  ffffe2e4205a  613e7b0df652       9.0
17453125  ffffe4376b38  91dab2a18dd5      15.0
17453126  ffffe43e3a7e  76706b9c2161      18.0
17453127  ffffe7ae42ed  c7b2eaf7e2f7      13.0
17453128  ffffe827e69e  fde42a0ca607      19.0
17453129  ffffe887c320  248102e50d79      13.0
17453130  ffffe8a7e9df  e427a6dc5967      13.0
17453131  ffffe8bd8942  2ea70a00de6f      18.0
17453132  ffffe8ee9eff  df1983d5a173       2.0
17453133  ffffea5c0275  6f098c9884d8      19.0
17453134  ffffeb2707bb  dd56792a6a94       6.0
17453135  ffffeb96b295  5f15600126c9      19.0
17453136  ffffec376565  c0a31a9d1ad4      13.0
17453137  ffffed319b63  8199647b2e9f      19.0
17453138  ffffeef47a6a  776b32b1081b      17.0
17453139  fffff14ef8df  a4c9ce12e036       6.0
17453140  fffff2eb996f  b9c54057380a      19.0
17453141  fffff3827b87  8f84f50c91ed      13.0
17453142  fffff422303b  eb534ece8551      13.0
17453143  fffff498f58e  3f5628988ba6      12.0
17453144  fffff4a89da0  a00145563f9a      12.0
17453145  fffff4c76151  92aa07608e0f       6.0
17453146  fffff5027aa3  4fb109b44261       3.0
17453147  fffff51881c3  b06d8adc668b      19.0
17453148  fffffba488e9  31632e7dad26       6.0
17453149  fffffc8b4631  97555bc3a4c1      15.0
17453150  fffffd2b4888  00ba4bbaa251      19.0
17453151  fffffed307d7  7c8bb14edb4f      14.0
17453152  ffffff369d59  9d279db71590      13.0
17453153  fffffffec760  41e8d5ba1b45      14.0

[17453154 rows x 3 columns]

In [ ]:
data=data.fillna(1)
gc.collect()

sumcount=data.groupby(['user_id']).dis_days.sum().reset_index()
sumcount.columns.values[1]='dis_days'

count=data.groupby(['user_id']).item_id.nunique().reset_index()
count.columns.values[1]='count'

data=pd.merge(sumcount, count, on=['user_id'],how='left')
data['dis_days']=data['dis_days']/data['count']
data=data.drop(['count'], axis=1)
gc.collect()
data['dis_days']=round(data['dis_days'],3)

data.to_csv('userdisplaydays.csv', index=False)
data

In [13]:
data[data['dis_days'].isnull()]

               item_id       user_id  dis_days
110304    019d22905ed7  b09f2aedbbb4       NaN
139856    020c2132dcf3  98dbf99fc12a       NaN
153776    0240039c39e8  542d28c53ad3       NaN
589124    08a46aafbd25  bb54ae6a855b       NaN
907177    0d5155abff45  8c6f0f482384       NaN
1251031   125e6ab1de6f  dfa261587f9f       NaN
1650570   183a331937aa  4e3d9332294f       NaN
1832338   1ae3621e36a4  030d962b516b       NaN
1941345   1c7c0cf56b5f  b0e4beeb69ba       NaN
2346745   2270c890b889  dc00c7e98fb6       NaN
2602027   2631eb00ae15  ff7e5360b2b8       NaN
2696471   27961e4c5237  dd6fe583ad57       NaN
2788389   28ed77c8ffac  7d3b0859f9df       NaN
2962045   2b7736b796c3  7bc855e5910d       NaN
3543663   33fa2e9dd9d5  3ca467b049f0       NaN
3649520   3586c7a25777  fe89a6ddaaa2       NaN
3732044   36badcc3fc80  37040f68f833       NaN
3794757   37a5af20a1ce  a592b70fc5bc       NaN
5036840   49db13db54f1  59a27e816f44       NaN
5042574   49f0729ea6de  e732202d359d       NaN
5311701   4de23ff8eb2c  f687aa705d3b       NaN
5364778   4ea9343fe69a  26c93b4caf1a       NaN
5543453   51477ee93513  514223d4ad45       NaN
5839305   559e4c347743  26866d5f8d0e       NaN
5853603   55d483c38359  5dd6440587e0       NaN
5940647   57192e9e6cb0  615446690606       NaN
6346333   5d0ad872dfbf  b9a2daae6878       NaN
6449898   5e91eda68a02  5ae28b4cf3b0       NaN
6641451   6162d41ee042  2010c893ff6e       NaN
7089226   67f1017de714  df2609d9ea70       NaN
...                ...           ...       ...
11307272  a5cf5f25fc3c  6df078011599       NaN
11557518  a97b0d23df09  436a421a7b6c       NaN
11758361  ac6d9639ab0d  ac366943c64f       NaN
11850410  adc69adb31cc  8ac0e6509fa1       NaN
12337449  b4ef799999f7  6880441732dd       NaN
12656504  b99e455d6b97  69b00783cd75       NaN
12698716  ba3c23a59823  405093748c23       NaN
13375452  c428d70af446  e8cbf33d9136       NaN
13415683  c4be7e02922f  9795061bccf1       NaN
13549578  c6b715644ac0  5c600c3e12bf       NaN
13591513  c7551edb4494  238525d05cf5       NaN
13622224  c7c8a4d49e9d  7ba28e8e83f3       NaN
13769358  c9f08a57c5ad  f698906efd47       NaN
13863329  cb509be656db  d1ae0e8c8fe3       NaN
14083081  ce898f34c5df  fdcbc2dfe6f7       NaN
14454622  d40060d7dc76  27eed44d3efa       NaN
14816034  d951d9c0d12c  385c380378bf       NaN
14973409  dba0c131627f  99492164b4d6       NaN
14996322  dbf639620cb6  7638deae8dc8       NaN
15066269  dcfcf763615e  6b0cb1b3fa57       NaN
15400869  e1e606655b98  772d6940b7c6       NaN
15486041  e324aaba2994  12b63900a60c       NaN
15739720  e6ddb4a418e7  69eeb3fb9ef5       NaN
15975938  ea53801a61c9  423f28ad55fb       NaN
16002924  eab905af24e9  db2d87f4569d       NaN
16062356  eb9863c55907  e45375928143       NaN
16063107  eb9b352d4d94  cd0c91a04b01       NaN
16227293  ee0233d38d89  59d97417f1f8       NaN
16450553  f148b5c644b1  eeeea7ae8d95       NaN
17000861  f95d82623f9d  0ae87b071254       NaN

[81 rows x 3 columns]

In [14]:
del result
gc.collect()

14

In [5]:
data[data['user_id']=='0000159771bd']

               item_id       user_id
350116    0523016e8082  0000159771bd
1736075   197a6b26c7ed  0000159771bd
3225187   2f50e47afabe  0000159771bd
3322241   30bccc331522  0000159771bd
3357454   3141106bb7a2  0000159771bd
4425686   40e11b00ed51  0000159771bd
6246977   5b96820e8cdc  0000159771bd
9223777   87396166fb5e  0000159771bd
9547484   8bfacbc5952a  0000159771bd
9910430   914eae05bc31  0000159771bd
10205615  95a762501f5b  0000159771bd
10939991  a06c1c404619  0000159771bd
12870616  bcc216c376d3  0000159771bd
12897864  bd2684313e35  0000159771bd
13961963  ccc278f27b65  0000159771bd
16472416  f19b6d53d3e2  0000159771bd
16919920  f82d2a4b20e4  0000159771bd

In [9]:
period[period['item_id']=='30bccc331522']

               item_id   date_from     date_to
15245284  30bccc331522  2017-03-15  2017-03-28
27307914  30bccc331522  2017-04-12  2017-04-18